# roles/netbox/tasks/database.yml v1.3
---

- name: Add internal PostgreSQL 15 repo
  ansible.builtin.copy:
    src: files/pg15.repo
    dest: /etc/yum.repos.d/pg15.repo
    mode: '0644'

- name: Install PostgreSQL 15 packages
  ansible.builtin.dnf:
    name:
      - postgresql15-server
      - postgresql15-devel
    state: present

- name: Check if PostgreSQL 15 is initialized
  stat:
    path: /var/lib/pgsql/15/data/postgresql.conf
  register: postgresql15_config

- name: Initialize PostgreSQL 15
  command: /usr/pgsql-15/bin/postgresql-15-setup initdb
  when: not postgresql15_config.stat.exists

- name: Start and enable PostgreSQL 15
  systemd:
    name: postgresql-15
    state: started
    enabled: yes

- name: Configure pg_hba.conf for NetBox user
  lineinfile:
    path: /var/lib/pgsql/15/data/pg_hba.conf
    regexp: '^host\s+{{ netbox_db_name }}\s+{{ netbox_db_user }}\s+127.0.0.1/32'
    line: "host    {{ netbox_db_name }}    {{ netbox_db_user }}    127.0.0.1/32    md5"
    state: present
  notify: restart postgresql

- name: Create NetBox user
  become: true
  become_user: postgres
  command: >
    /usr/pgsql-15/bin/psql -c "CREATE ROLE {{ netbox_db_user }} WITH LOGIN ENCRYPTED PASSWORD '{{ netbox_db_password }}';"
  register: create_user_result
  failed_when:
    - create_user_result.rc != 0
    - "'already exists' not in create_user_result.stderr"
  changed_when: "'already exists' not in create_user_result.stderr"

- name: Create NetBox database
  become: true
  become_user: postgres
  command: >
    /usr/pgsql-15/bin/psql -c "CREATE DATABASE {{ netbox_db_name }} WITH OWNER {{ netbox_db_user }};"
  register: create_db_result
  failed_when:
    - create_db_result.rc != 0
    - "'already exists' not in create_db_result.stderr"
  changed_when: "'already exists' not in create_db_result.stderr"
