# roles/netbox/tasks/dependencies.yml v1.3 – angepasst für PostgreSQL 15 auf Rocky 9.5
---

- name: Install dependencies
  ansible.builtin.dnf:
    name:
      - python3
      - python3-devel
      - python3-pip
      - git
      - gcc
      - libxml2-devel
      - libxslt-devel
      - libffi-devel
      - openssl-devel
      - redhat-rpm-config
      - postgresql15-server
      - postgresql15-devel
      - nginx
      - redis
    state: present

- name: Create system group
  ansible.builtin.group:
    name: "{{ netbox_group }}"
    state: present

- name: Create system user
  ansible.builtin.user:
    name: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    home: "{{ netbox_home }}"
    shell: /bin/bash
    system: true
    createhome: false
