# roles/netbox/tasks/dependencies.yml v1.4 – PostgreSQL 15 via AppStream
---

- name: Enable PostgreSQL 15 module
  ansible.builtin.command: dnf module enable postgresql:15 -y
  changed_when: true

- name: Install dependencies
  ansible.builtin.dnf:
    name:
      - python3
      - python3-devel
      - python3-pip
      - git
      - gcc
      - libxml2-devel
      - libxslt-devel
      - libffi-devel
      - openssl-devel
      - redhat-rpm-config
      - postgresql-server
      - postgresql-devel
      - nginx
      - redis
    state: present

- name: Create system group
  ansible.builtin.group:
    name: "{{ netbox_group }}"
    state: present

- name: Create system user
  ansible.builtin.user:
    name: "{{ netbox_user }}"
    group: "{{ netbox_group }}"
    home: "{{ netbox_home }}"
    shell: /bin/bash
    system: true
    createhome: false