# roles/netbox/tasks/nginx.yml v1.1
---
- name: Configure Nginx
  ansible.builtin.template:
    src: nginx_netbox.conf.j2
    dest: /etc/nginx/conf.d/netbox.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart Nginx

- name: Remove default Nginx configuration
  ansible.builtin.file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: Restart Nginx

- name: Start and enable Nginx
  ansible.builtin.systemd:
    name: nginx
    state: started
    enabled: true