# roles/netbox/tasks/systemd.yml v1.1
---
- name: Configure NetBox systemd services
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: '0644'
  with_items:
    - { src: 'netbox.service.j2', dest: '/etc/systemd/system/netbox.service' }
    - { src: 'netbox-rq.service.j2', dest: '/etc/systemd/system/netbox-rq.service' }
  notify:
    - Reload systemd
    - Restart NetBox services

- name: Enable and start NetBox services
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items:
    - netbox
    - netbox-rq